"""Node linked sequence relationships

Revision ID: 3a4500674eef
Revises: 1fae884e42cc
Create Date: 2023-09-06 15:42:27.050727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a4500674eef"
down_revision = "1fae884e42cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pathway_sequence",
        sa.Column("before_id", sa.UUID(), nullable=False),
        sa.Column("after_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["after_id"], ["node.id"], ),
        sa.ForeignKeyConstraint(["before_id"], ["node.id"], ),
        sa.PrimaryKeyConstraint("before_id", "after_id")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pathway_sequence")
    # ### end Alembic commands ###
