"""Featured groups pathways

Revision ID: 78810d57a727
Revises: ddef2f9672c9
Create Date: 2023-10-25 11:19:41.144268

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "78810d57a727"
down_revision = "ddef2f9672c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("group", sa.Column("isFeatured", sa.Boolean(), server_default=sa.sql.false(), nullable=False))
    op.add_column("pathway", sa.Column("isFeatured", sa.Boolean(), server_default=sa.sql.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pathway", "isFeatured")
    op.drop_column("group", "isFeatured")
    # ### end Alembic commands ###
