"""Adding group user search vectors

Revision ID: ddef2f9672c9
Revises: b0847f8dacd3
Create Date: 2023-10-25 09:38:00.482651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import TSVectorType


# revision identifiers, used by Alembic.
revision = "ddef2f9672c9"
down_revision = "b0847f8dacd3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group",
        sa.Column(
            "title_vector",
            TSVectorType(),
            sa.Computed("to_tsvector('pg_catalog.simple', \"title\")", persisted=True),
            nullable=True,
        ),
    )
    op.add_column(
        "group",
        sa.Column(
            "description_vector",
            TSVectorType(),
            sa.Computed("to_tsvector('pg_catalog.simple', \"description\")", persisted=True),
            nullable=True,
        ),
    )
    op.create_index("ix_group_description_vector", "group", ["description_vector"], unique=False, postgresql_using="gin")
    op.create_index("ix_group_title_vector", "group", ["title_vector"], unique=False, postgresql_using="gin")
    op.add_column(
        "user",
        sa.Column(
            "description_vector",
            TSVectorType(),
            sa.Computed("to_tsvector('pg_catalog.simple', \"description\")", persisted=True),
            nullable=True,
        ),
    )
    op.create_index("ix_user_description_vector", "user", ["description_vector"], unique=False, postgresql_using="gin")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_description_vector", table_name="user", postgresql_using="gin")
    op.drop_column("user", "description_vector")
    op.drop_index("ix_group_title_vector", table_name="group", postgresql_using="gin")
    op.drop_index("ix_group_description_vector", table_name="group", postgresql_using="gin")
    op.drop_column("group", "description_vector")
    op.drop_column("group", "title_vector")
    # ### end Alembic commands ###
