
name: Deploy to production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User root
            IdentityFile ~/.ssh/deploy.key
          END
          ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts
        env:
          SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
          SSH_HOST: 178.62.71.194

      - name: Check out the latest code
        run: ssh server 'cd /srv/obaluaye && git pull'
      
      - name: Run the build script
        run: |
          ssh server 'cd /srv/obaluaye && \
          TAG=prod \
          DOMAIN=globalhealthstudybuilder.org \
          STACK_NAME=globalhealthstudybuilder-org \
          TRAEFIK_TAG=globalhealthstudybuilder.org \
          FRONTEND_ENV=prod \
          bash -x scripts/build.sh'

      - name: Remove existing stack and prune images
        run: |
          ssh server 'docker stack rm globalhealthstudybuilder-org && \
          sleep 60 && \
          docker image prune -f'

      - name: Run the deploy script
        run: |
          ssh server 'cd /srv/obaluaye && \
          TAG=prod \
          DOMAIN=globalhealthstudybuilder.org \
          STACK_NAME=globalhealthstudybuilder-org \
          TRAEFIK_TAG=globalhealthstudybuilder.org \
          bash -x scripts/deploy.sh'